# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  domain_name: example.com
  secret_key_base: 1cbcb1cfb04d16855b50f9d05a306bb40ece187b471487bcb9b931adc2848472dd3ed4bdd53f19797d4a995a344b6ef0129096060c42d7c1a2ab506c896da1fb

test:
  domain_name: example.com 
  secret_key_base: 8b64fc057e7309f96bb6cfb93201766ecca68043aa6a8f6fd0fcfaeb1d23529720713ef21bf1a1f36fa6ad2f425909c3973aae3ebe0af9390429770b3ca84000

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
